# Generated by Django 3.0.4 on 2020-04-13 13:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=20, verbose_name='First Name')),
                ('lname', models.CharField(max_length=20, verbose_name='Last Name')),
                ('addr', models.CharField(max_length=50, verbose_name='Address')),
                ('acct_num', models.IntegerField(verbose_name='Account Number')),
                ('mobile_num', models.IntegerField(verbose_name='Mobile Number')),
                ('email_addr', models.EmailField(max_length=200, verbose_name='Email Address')),
                ('created_by', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
