# Generated by Django 3.0.4 on 2020-04-04 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.TextField(max_length=200, verbose_name='User Name')),
                ('password', models.TextField(max_length=200, verbose_name='Password')),
                ('role', models.TextField(max_length=200, verbose_name='Role')),
            ],
        ),
    ]
