# Generated by Django 3.0.4 on 2020-05-02 07:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=20, verbose_name='First Name')),
                ('lname', models.CharField(max_length=20, verbose_name='Last Name')),
                ('addr', models.CharField(max_length=50, verbose_name='Address')),
                ('acct_num', models.IntegerField(verbose_name='Account Number')),
                ('mobile_num', models.IntegerField(verbose_name='Mobile Number')),
                ('email_addr', models.EmailField(max_length=200, verbose_name='Email Address')),
                ('balance', models.FloatField(verbose_name='Account Balance')),
                ('created_by', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WithdrawTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trx_date', models.DateField(verbose_name='Date')),
                ('trx_ref', models.CharField(max_length=10, verbose_name='Reference #')),
                ('status', models.CharField(max_length=50, verbose_name='Status')),
                ('withdraw_amt', models.FloatField(verbose_name='Withdraw Amount')),
                ('curr', models.CharField(default='PHP', max_length=20, verbose_name='Currency')),
                ('current_balance', models.FloatField(verbose_name='Current Balance')),
                ('total_balance', models.FloatField(verbose_name='Total Balance')),
                ('client', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='bank.Client')),
                ('created_by', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TransferTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trx_date', models.DateField(verbose_name='Date')),
                ('trx_ref', models.CharField(max_length=10, verbose_name='Reference #')),
                ('status', models.CharField(max_length=50, verbose_name='Status')),
                ('transfer_amt', models.FloatField(verbose_name='Transfer Amount')),
                ('curr', models.CharField(default='PHP', max_length=20, verbose_name='Currency')),
                ('created_by', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('from_client', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='from_client', to='bank.Client')),
                ('to_client', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='to_client', to='bank.Client')),
            ],
        ),
        migrations.CreateModel(
            name='DepositTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trx_date', models.DateField(verbose_name='Date')),
                ('trx_ref', models.CharField(max_length=10, verbose_name='Reference #')),
                ('status', models.CharField(max_length=50, verbose_name='Status')),
                ('deposit_amt', models.FloatField(verbose_name='Deposit Amount')),
                ('curr', models.CharField(default='PHP', max_length=20, verbose_name='Currency')),
                ('current_balance', models.FloatField(verbose_name='Current Balance')),
                ('total_balance', models.FloatField(verbose_name='Total Balance')),
                ('client', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='bank.Client')),
                ('created_by', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
