# Generated by Django 3.0.4 on 2020-04-12 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0002_auto_20200404_1643'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=20, verbose_name='First Name')),
                ('lname', models.CharField(max_length=20, verbose_name='Last Name')),
                ('addr', models.CharField(max_length=50, verbose_name='Address')),
                ('acct_num', models.IntegerField(max_length=200, verbose_name='Account Number')),
                ('mobile_num', models.IntegerField(max_length=200, verbose_name='Mobile Number')),
                ('email_addr', models.CharField(max_length=200, verbose_name='Email Address')),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
