# Generated by Django 3.0.4 on 2020-04-13 14:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bank', '0003_client_created_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='DepositTrx',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trx_date', models.DateField(auto_now_add=True, verbose_name='Date')),
                ('trx_ref', models.CharField(default='4358723508', max_length=10)),
                ('status', models.CharField(max_length=50, verbose_name='Status')),
                ('deposit_amt', models.FloatField(verbose_name='Deposit Amount')),
                ('curr', models.CharField(max_length=20, verbose_name='Currency')),
                ('current_balance', models.FloatField(verbose_name='Current Balance')),
                ('total_balance', models.FloatField(verbose_name='Total Balance')),
                ('client', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='bank.Client')),
                ('created_by', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
