# Generated by Django 3.0.4 on 2020-04-18 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0005_auto_20200413_2247'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='balance',
            field=models.FloatField(default=1, verbose_name='Account Balance'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='deposittransaction',
            name='trx_ref',
            field=models.CharField(default='5559525114', max_length=10),
        ),
        migrations.AlterField(
            model_name='withdrawtransaction',
            name='trx_ref',
            field=models.CharField(default='4911498769', max_length=10),
        ),
    ]
