# Generated by Django 3.0.4 on 2020-04-18 13:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bank', '0006_auto_20200418_1604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deposittransaction',
            name='curr',
            field=models.CharField(default='PHP', max_length=20, verbose_name='Currency'),
        ),
        migrations.AlterField(
            model_name='deposittransaction',
            name='trx_ref',
            field=models.CharField(default='4577821899', max_length=10),
        ),
        migrations.AlterField(
            model_name='withdrawtransaction',
            name='curr',
            field=models.CharField(default='PHP', max_length=20, verbose_name='Currency'),
        ),
        migrations.AlterField(
            model_name='withdrawtransaction',
            name='trx_ref',
            field=models.CharField(default='9257001006', max_length=10),
        ),
        migrations.AlterField(
            model_name='withdrawtransaction',
            name='withdraw_amt',
            field=models.FloatField(verbose_name='Withdraw Amount'),
        ),
        migrations.CreateModel(
            name='TransferTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trx_date', models.DateField(auto_now_add=True, verbose_name='Date')),
                ('trx_ref', models.CharField(default='3294504906', max_length=10)),
                ('status', models.CharField(max_length=50, verbose_name='Status')),
                ('transfer_amt', models.FloatField(verbose_name='Transfer Amount')),
                ('curr', models.CharField(default='PHP', max_length=20, verbose_name='Currency')),
                ('created_by', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('from_client', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='from_client', to='bank.Client')),
                ('to_client', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='to_client', to='bank.Client')),
            ],
        ),
    ]
