# Generated by Django 3.0.4 on 2020-04-19 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0007_auto_20200418_2148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deposittransaction',
            name='trx_ref',
            field=models.CharField(default='3329305046', max_length=10),
        ),
        migrations.AlterField(
            model_name='transfertransaction',
            name='trx_ref',
            field=models.CharField(default='7034290517', max_length=10),
        ),
        migrations.AlterField(
            model_name='withdrawtransaction',
            name='trx_ref',
            field=models.CharField(default='7185415086', max_length=10),
        ),
    ]
